feed/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

#static files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    #home url
    path('', home, name='home'),

    #apps include
    path('accounts/', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('production/', include('production.urls')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from .views import *

app_name = 'inventory' # This name important for reverse lookup


urlpatterns = [
    path('list/', InventoryView.as_view(), name='inventory-list'),
    path('ingredient/update/<int:pk>/', IngredientUpdateView.as_view(), name='ingredient-update'),
    path('ingredient/delete/<int:pk>/', IngredientDeleteView.as_view(), name='ingredient-delete'),
    path('search/', search_ingredient, name="ingredient-search"),
]

inventory/models.py
from django.db import models
from django.core.validators import MinValueValidator
from production.constants import Unit, UNIT_TO_KG

# Create your models here.

class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True) # this sets all different ingredient is used
    description = models.TextField(blank=True)
    unit = models.CharField(max_length=2,
                            choices=Unit.choices,
                            default=Unit.KILOGRAMS)
    previous_stock = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    current_stock = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    added_stock = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    min_threshold = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cost_per_unit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_by = models.ForeignKey('accounts.CustomUser', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name   

class StockUpdate(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(0.01)])
    timestamp = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey('accounts.CustomUser', on_delete=models.SET_NULL, null=True)
    note = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        #update current stock
        self.ingredient.current_stock += self.quantity
        self.ingredient.save()

inventory/forms.py
from django.forms import ModelForm
from .models import *

class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields =['name', 'description', 'unit', 'cost_per_unit', 'added_stock', 'min_threshold']

class IngredientUpdateForm(ModelForm):
    class Meta:
        model=StockUpdate
        fields = ['ingredient', 'quantity', 'note']

inventory/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.mixins import InventoryRequiredMixin
from accounts.decorators import inventory_required, admin_required
from django.db.models import F
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from django.views.generic.edit import FormView
from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Ingredient, StockUpdate
from .forms import IngredientForm, IngredientUpdateForm

class InventoryView(LoginRequiredMixin, InventoryRequiredMixin, FormView):
    template_name = 'inventory/inventory_dash.html'
    form_class = IngredientForm
    success_url = reverse_lazy('inventory:inventory-list')  # make sure this URL name exists

    def test_func(self):
        return self.request.user.user_type in ['admin', 'inventory' ]

    def form_valid(self, form):
        ingredient = form.save(commit=False)
        ingredient.created_by = self.request.user
        ingredient.previous_stock = ingredient.current_stock
        ingredient.current_stock += ingredient.added_stock
        ingredient.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ingredients'] = Ingredient.objects.order_by('name')
        context['re_ingredients'] = Ingredient.objects.order_by('-created_at')
        context['low_stock'] = Ingredient.objects.filter(
            current_stock__lt=F('min_threshold')
        )
        return context
    

# Add to existing views.py
class IngredientUpdateView(LoginRequiredMixin, InventoryRequiredMixin,  UpdateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = 'inventory/invt_update.html'
    success_url = reverse_lazy('inventory:inventory-list')

    def form_valid(self, form):
        update = form.save(commit=False)
        update.updated_by = self.request.user
        update.previous_stock = update.current_stock
        update.current_stock += update.added_stock
        return super().form_valid(form)
    
    
class IngredientDeleteView(SuccessMessageMixin, InventoryRequiredMixin,  DeleteView):
    model = Ingredient
    template_name = 'inventory/inv_delete.html'
    success_url = reverse_lazy('inventory:inventory-list')
    success_message = "Ingredient deleted successfully."


@inventory_required
def search_ingredient(request):
    query = request.GET.get('q', '') #get query from url
    form = IngredientForm()
    re_ingredients = Ingredient.objects.order_by('-created_at')
    if query:
        ingredients = Ingredient.objects.filter(name__icontains=query)
    else:
        ingredients = Ingredient.objects.all()
    context ={
        'ingredients':ingredients,
        'query':query, 
        'form':form,
        're_ingredients': re_ingredients
    }
    return render(request, 'inventory/inventory_dash.html', context=context)

templates/inventory/inv_delete.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/inventory.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Inventory Management{% endblock %}

{% block content %}

<div class="delete-page">
    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete ingredient - "{{ object.name }}"?</p>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn-danger">Yes, delete</button>
    </form>
    <div>
        <a href="{% url 'inventory:inventory-list' %}">Cancel</a>
    </div>
</div>

{% endblock %}

{% block script %} {% endblock %}

templates/inventory/inventory_dash.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/inventory.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Inventory Management{% endblock %}

{% block content %}

<div class="invt-container">
    <div class="invt-list">
        <div class="top">
            <!-- search  bar -->
            <form method="GET" action="{% url 'inventory:ingredient-search' %}" class="search-form">
                <div class="search-container">
                    <span class="material-symbols-outlined">search</span>
                    <input 
                    type="text" 
                    name="q" 
                    placeholder="Search inventory items" 
                    class="search-input" 
                    />
                </div>
            </form>
        </div>
        <!-- end serach bar -->
         <!-- Inventory table start -->
        <div class="inventory">
            <div class="inventory-info">
                <p>Total Inventory items: {{ingredients.count}}
                </p>
            </div>
            <h2>Inventory List</h2>
            {% if ingredients %}
            <table border="1" class="inventory-table">
                <tr>
                    <th>S.N.</th>
                    <th>Name</th>
                    <th>Unit</th>
                    <th>Previous Stock</th>
                    <th>Current Stock</th>
                    <th>Added Stock</th>
                    <th>Created By</th>
                    <th>Action</th>
                </tr>
                {% for ingredient in ingredients %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{ingredient.name}}</td>
                    <td>{{ingredient.unit}}</td>
                    <td>{{ingredient.previous_stock}}</td>
                    <td>{{ingredient.current_stock}}</td>
                    <td>{{ingredient.added_stock}}</td>
                    <td>{{ingredient.created_by}}</td>
                    <td>
                        <div>
                            <span class="update-item"><a href="{% url 'inventory:ingredient-update' ingredient.pk %}">Update</a></span>
                        <span class="delete-item"><a href="{% url 'inventory:ingredient-delete' ingredient.pk %}">Delete</a></span>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <p>No inventory available</p>
            {% endif %}
            
            
        </div>
        <!-- end table inventory -->
         
        <!-- Form for Ingredient add -->
        <div class="add-ingredient">
            <h2>Create New Ingredient</h2>
            <form action="{% url 'inventory:inventory-list' %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                {{field.label_tag}}
                {{field}}
                {{field.errors}}
                {% endfor %}
                <input type="submit" value="Submit">
            </form>
            
        </div>
        <!-- form end -->
    </div>
    <div class="invt-right">
        <div class="inventory-recent">
            <h2>Recent Added Ingredients</h2>
            {% for i in re_ingredients %}
            <div>
                <strong>{{ i.created_by }}</strong> 
                added {{i.added_stock}} {{i.unit}}
                of {{i.name}}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

{% block script %} {% endblock %}

templates/inventory/invt_update.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/inventory.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Inventory Update{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{% if object %}Update{% else %}Create{% endif %} Ingredient</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'inventory:inventory-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>


{% endblock %}

{% block script %} {% endblock %}