accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts' # This name important for reverse lookup


urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

feed/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

#static files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    #home url
    path('', home, name='home'),

    #apps include
    path('accounts/', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('production/', include('production.urls')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from .views import *

app_name = 'inventory' # This name important for reverse lookup


urlpatterns = [
    path('list/', InventoryView.as_view(), name='inventory-list'),
    path('ingredient/update/<int:pk>/', IngredientUpdateView.as_view(), name='ingredient-update'),
    path('ingredient/delete/<int:pk>/', IngredientDeleteView.as_view(), name='ingredient-delete'),
    path('search/', search_ingredient, name="ingredient-search"),
]

production/urls.py
from django.urls import path
from .views import *

app_name = 'production' # This name important for reverse lookup


urlpatterns = [
    path('formula_create/', CreateFormulaView.as_view(), name='formula-create'),
    path('formula_detail/<int:pk>/', FormulaDetailView.as_view(), name='formula-detail'),
    path('formula/<int:pk>/delete/', FormulaDeleteView.as_view(), name='formula-delete'),
    path('formula/<int:formula_id>/ingredient/<int:pk>/delete/',FormulaIngredientDelete.as_view(), name='foring-delete'),
    path('production_view/', ProductionView.as_view(), name='production'),
    path('production/detail/<int:pk>/', ProductionDetailView.as_view(), name='production-detail'),
    # path('register/', views.register_view, name='register'),
]

templates/basic/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block stylesheet %} {% endblock %}
    <title>Feed Formulatio - {% block title %} {% endblock %}</title>
    
</head>
<body>
    <!-- navbar start -->
    <!-- {% include 'basic/navbar.html' %} -->
    <!-- navbar end -->

    <!-- this section is for messages -->
    {% if messages %}
    {% for message in messages %}
    <div class="message-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <!-- section end -->

    <!-- here main content block -->
    {% block content %}

    {% endblock %}
    <!-- end of main content block -->

    <!-- footer section -->
    {% block footer %}
    {% endblock %}
    <!-- end footer -->

    <!-- javascript -->
    {% block script %} {% endblock %}
    <!-- end javascript -->
    
</body>
</html>

templates/basic/footer.html
<div class="footer">
    <p>Copyright &copy; Subivet Lab & Consultancy-{% now 'Y' %} </p>
</div>

templates/basic/home.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Home page {% endblock %}

{% block content %}

<!-- Home page -->
<div class="home-container">

    <!-- Hero section of Home page -->
    <div class="hero-section">
        <div class="hero-left">
            <h1 class="head ">Feed Formulation System</h1>
            <p class="para">Make Feed Formulation more robust and efficient for better production environment that supports business motives.</p>
        </div>
        <div class="hero-right">
            <img src="{% static 'img/poultry.png' %}" alt="feed formation">
        </div>
    </div>

    <!-- Our services section -->
     <div class="services-content">
        <h1>OUR SERVICES</h1>
        <div class="services">
            <div class="service">
                <div class="home-card">
                    <div class="top">INVENTORY</div>
                    <hr>
                    <div class="body">
                        <p>Lorem ipsum dolor sit amet consectetur 
                            adipisicing elit. Ipsam ea, architecto 
                            consequuntur saepe, eum, vero ipsa enim 
                            impedit eos explicabo earum at ab quod. 
                            Neque, reprehenderit! Repudiandae
                            quisquam amet perspiciatis?</p>
                    </div>
                    <div class="bottom">
                        <a href="{% url 'inventory:inventory-list' %}">Inventory</a>
                    </div>
                </div>
            </div>
            <div class="service">
                <div class="home-card">
                    <div class="top">PRODUCTION</div>
                    <hr>
                    <div class="body">
                        <p>Lorem ipsum dolor sit amet consectetur 
                            adipisicing elit. Ipsam ea, architecto 
                            consequuntur saepe, eum, vero ipsa enim 
                            impedit eos explicabo earum at ab quod. 
                            Neque, reprehenderit! Repudiandae
                            quisquam amet perspiciatis?</p>
                    </div>
                    <div class="bottom">
                        <a href="{% url 'production:production' %}">Production</a>
                    </div>
                </div>
            </div>
            <div class="service">
                <div class="home-card">
                    <div class="top">DASHBOARD</div>
                    <hr>
                    <div class="body">
                        <p>Lorem ipsum dolor sit amet consectetur 
                            adipisicing elit. Ipsam ea, architecto 
                            consequuntur saepe, eum, vero ipsa enim 
                            impedit eos explicabo earum at ab quod. 
                            Neque, reprehenderit! Repudiandae
                            quisquam amet perspiciatis?</p>
                    </div>
                    <div class="bottom">
                        <a href="#">Dashboard</a>
                    </div>
                </div>
            </div>
        </div>
     </div>
    
    <!-- end of our services -->

    <!-- Testimonials -->
     <!-- <div class="testimonials">
        <div class="testop"><h1>Testimonials</h1></div>
     </div> -->
</div>


{% endblock %}

{% block script %} {% endblock %}

templates/basic/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    {% block stylesheet %} {% endblock %}
    <title>Feed Formulatio - {% block title %} {% endblock %}</title>
    
</head>
<body>
    <!-- navbar start -->
    {% include 'basic/navbar.html' %}
    <!-- navbar end -->

    <!-- this section is for messages -->
    {% if messages %}
    {% for message in messages %}
    <div class="message-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <!-- section end -->

    <!-- here main content block -->
    {% block content %}

    {% endblock %}
    <!-- end of main content block -->

    <!-- footer section -->
    {% block footer %}
    {% include 'basic/footer.html' %}
    {% endblock %}
    <!-- end footer -->

    <!-- javascript -->
    {% block script %} {% endblock %}
    <!-- end javascript -->
    
</body>
</html>

templates/basic/navbar.html
{% load static %}

<div class="navbar">
    <div class="navbar-logo">
        <p><a href="{% url 'home' %}">Subi<span id="vet">Vet</span></a><br>
            <span>
                <em>Lab & Consultancy</em>
            </span>
        </p>
    </div>
    <div class="navbar-menu">
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'inventory:inventory-list' %}">Inventory</a></li>
            <li><a href="{% url 'production:formula-create' %}">Formula</a></li>
            <li><a href="{% url 'production:production' %}">Production</a></li>
            <li><a href="#">Reports</a></li>
        </ul>
    </div>
    <div class="navbar-end">
        <ul>
            {% if request.user.is_authenticated %}
            <li><a href="#">{{request.user.username}}</a></li>
            
            <li><a href="{% url 'accounts:logout' %}">
                  <button id="btnlogout">Logout</button>
                </a>
            </li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">
                  <button id="btnlogin">Login</button>
                </a>
            </li>
            <li><a href="{% url 'accounts:register' %}">
                  <button id="btnregister">Register</button>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
<hr>