feed/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

#static files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    #home url
    path('', home, name='home'),

    #apps include
    path('accounts/', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('production/', include('production.urls')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

production/urls.py
from django.urls import path
from .views import *

app_name = 'production' # This name important for reverse lookup


urlpatterns = [
    path('formula_create/', CreateFormulaView.as_view(), name='formula-create'),
    path('formula_detail/<int:pk>/', FormulaDetailView.as_view(), name='formula-detail'),
    path('formula/<int:pk>/delete/', FormulaDeleteView.as_view(), name='formula-delete'),
    path('formula/<int:formula_id>/ingredient/<int:pk>/delete/',FormulaIngredientDelete.as_view(), name='foring-delete'),
    path('production_view/', ProductionView.as_view(), name='production'),
    path('production/detail/<int:pk>/', ProductionDetailView.as_view(), name='production-detail'),
    # path('register/', views.register_view, name='register'),
]

production/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from inventory.models import StockUpdate
from .constants import Unit, UNIT_TO_KG
from django.core.exceptions import ValidationError

# Create your models here.

class Formula(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey('accounts.CustomUser', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class FormulaIngredient(models.Model):
    formula = models.ForeignKey(Formula,
                                on_delete=models.CASCADE,
                                related_name='ingredients')
    ingredient = models.ForeignKey('inventory.Ingredient',
                                   on_delete=models.CASCADE)
    percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0.01), MaxValueValidator(100)]
    )

    def __str__(self):
        return self.ingredient.name


class ProductionBatch(models.Model):
    formula = models.ForeignKey(Formula, on_delete=models.PROTECT)
    unit = models.CharField(
        max_length=2, choices=Unit.choices, default=Unit.TONNES)
    batch_size = models.DecimalField(
        max_digits=15, decimal_places=2,
        validators=[MinValueValidator(0.1)])
    production_date = models.DateTimeField(auto_now_add=True)
    produced_by = models.ForeignKey('accounts.CustomUser',
                                     on_delete=models.SET_NULL,
                                     null=True)
    notes = models.TextField(blank=True)

    def clean(self):
        #validate stock levels befor saving
        for comp in self.formula.ingredients.all():
            #convert the batch size to kg (common unit)
            batch_size_kg = self.batch_size * UNIT_TO_KG[self.unit]
            # print(UNIT_TO_KG[self.unit])
            quantity_needed_kg = (comp.percentage / 100) * batch_size_kg

            #now convert ingredient stock to kg
            ingredient = comp.ingredient
            stock_kg = ingredient.current_stock * UNIT_TO_KG[ingredient.unit.lower()]

            #validate needed and stock are equal or greater than
            if quantity_needed_kg > stock_kg:
                raise ValidationError(
                    f"Insuffient Stock for {ingredient.name}."
                    f"Needed: {quantity_needed_kg} Kg , Available: {stock_kg} Kg.")
            return quantity_needed_kg
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        #update stock levels
        for comp in self.formula.ingredients.all():
            batch_size_kg = self.batch_size * UNIT_TO_KG[self.unit]
            quantity_used_kg = (comp.percentage / 100) * batch_size_kg

            #convert bak to the ingredients original unit for deduction
            ingredient = comp.ingredient
            quantity_used_in_ingredient_unit = quantity_used_kg / UNIT_TO_KG[ingredient.unit.lower()]

            #now update stocks
            StockUpdate.objects.create(
                ingredient= ingredient,
                quantity =- quantity_used_in_ingredient_unit,
                updated_by = self.produced_by,
                note = f'Used in production batch #{self.id}'
            )
    
    def get_ingredients(self):
        return self.formula.ingredients.select_related('ingredient')
    

production/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from inventory.models import Ingredient

class FormulaForm(ModelForm):
    class Meta:
        model = Formula
        fields=['name', 'description']
        labels ={
            'name': 'Name of the Formula',
            'description': 'Description About Formula'
        }


class FormulaIngredientForm(ModelForm):
    class Meta:
        model = FormulaIngredient
        fields =['formula','ingredient', 'percentage']

#creating Formula Ingredient Formset
FormulaIngredientFormSet = forms.inlineformset_factory(
    Formula,
    FormulaIngredient,
    form=FormulaIngredientForm,
    extra=60,  # Show 5 empty ingredient slots by default
    can_delete=False,
    min_num=1,  # At least one ingredient required
    validate_min=True,
    max_num=60,  # Maximum ingredients per formulation
    validate_max=True,
)

class ProductionBatchForm(ModelForm):
    class Meta:
        model=ProductionBatch
        fields=['formula', 'unit', 'batch_size', 'notes']
        labels={
            'unit': "Select Production Unit"
        }

production/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import ListView, DetailView
from django.db.models.deletion import ProtectedError
from django.contrib import messages
from .constants import Unit, UNIT_TO_KG
from django.db.models import *
from accounts.mixins import AdminRequiredMixin, ProducerRequiredMixin

# from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from inventory.models import Ingredient
from .models import *
from .forms import *

# Create your views here.
class CreateFormulaView(AdminRequiredMixin, CreateView):
    model = Formula
    form_class= FormulaForm
    template_name = 'production/formula_create.html'

    def test_func(self):
        return self.request.user.user_type in ['admin', 'producer' ]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formulas'] = Formula.objects.order_by('-updated_at')
        if self.request.POST:
            context['ingredient_formset']= FormulaIngredientFormSet(self.request.POST)
        else:
            context['ingredient_formset']= FormulaIngredientFormSet()
        return context
    
    def get_success_url(self):
        return reverse('production:formula-detail', kwargs={'pk': self.object.pk})
    
    def form_valid(self, form):
        context = self.get_context_data()
        ingredient_formset = context['ingredient_formset']
        if ingredient_formset.is_valid():
            self.object = form.save(commit=False)
            self.object.created_by = self.request.user
            self.object.save()
            ingredients= ingredient_formset.save(commit=False)
            for ingredient in ingredients:
                ingredient.formula = self.object
                ingredient.save()
            return redirect(self.get_success_url())
        return self.render_to_response(self.get_context_data(form = form))


class FormulaDetailView(AdminRequiredMixin, DetailView):
    model = Formula
    template_name = 'production/formula_detail.html'
    context_object_name = 'formula'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = self.object.ingredients.select_related('ingredient')  # Get related FormulaItem objects
        return context
    

# Formula delete view from formula createlist
class FormulaDeleteView(AdminRequiredMixin, DeleteView):
    model = Formula
    template_name = 'production/formula_delete.html'
    success_url = reverse_lazy('production:formula-create')


class FormulaIngredientDelete(AdminRequiredMixin, DeleteView):
    model = FormulaIngredient
    template_name= 'production/for_ing_delete.html'
    success_message = "Igredient removed from formula successfully"

    def get_object(self, queryset = None):
        formula_id = self.kwargs['formula_id']
        pk = self.kwargs['pk']
        return get_object_or_404(FormulaIngredient, pk=pk, formula__pk = formula_id)

    def get_success_url(self):
        formula_id = self.kwargs.get('formula_id')
        return reverse_lazy('production:formula-detail', kwargs={'pk': formula_id})
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            return super().delete(request, *args, **kwargs)
        except ProtectedError:
            messages.error(request, "Cannot delete this formula because it is used in a production batch.")
            return redirect(self.success_url)



class ProductionView(ProducerRequiredMixin, CreateView):
    model = ProductionBatch
    template_name= 'production/production.html'
    success_url= reverse_lazy('production/production_view/')
    fields=['formula', 'unit', 'batch_size', 'notes']

    def get_success_url(self):
        return reverse('production:production-detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['productions']= ProductionBatch.objects.order_by('-production_date')
        if self.request.POST:
            context['prod_form']= ProductionBatchForm(self.request.POST)
        else:
            context['prod_form']= ProductionBatchForm()
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        prod_form = context['prod_form']
        if prod_form.is_valid():
            self.object = prod_form.save(commit=False)
            self.object.produced_by = self.request.user
            self.object.save()
        return redirect(self.get_success_url())



class ProductionDetailView(ProducerRequiredMixin, DetailView):
    model=ProductionBatch
    template_name = 'production/production_detail.html'
    context_object_name='production'
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        ingredients = self.object.formula.ingredients.select_related('ingredient')
        # Aggregare percentage
        total_percentage = self.object.formula.ingredients.aggregate(
            Sum('percentage')
        )['percentage__sum'] or 0
        # print(f'Total Ingredient Percentage : {total_percentage}')

        #Total consumed stock

        #calculate the consumed quantity
        total_consumed =0
        ingredients_with_quantity =[]
        batch_size_kg = self.object.batch_size * UNIT_TO_KG[self.object.unit]
        for i in ingredients:
            if i.ingredient.unit == Unit.TONNES:
                i.ingredient.unit = Unit.KILOGRAMS
                print(f'Unit: {i.ingredient.unit}')
                return i.ingredient.unit
            ingredient_quantity_kg = (i.percentage/100) * batch_size_kg
            # All three quantity returns in Kilograms
            current_quantity_kg = i.ingredient.current_stock * UNIT_TO_KG[i.ingredient.unit]
            previous_stock_kg = i.ingredient.previous_stock * UNIT_TO_KG[i.ingredient.unit]
            total_consumed += ingredient_quantity_kg
            ingredients_with_quantity.append({
                'ingredient': i.ingredient.name,
                'percentage': i.percentage,
                'unit': i.ingredient.unit,
                'previous_stock': previous_stock_kg,
                'consumed_quantity': ingredient_quantity_kg,
                'current_stock': current_quantity_kg
            })
        context['ingredients'] = ingredients_with_quantity
        context['total_percentage']=total_percentage
        context['total_consumed'] = total_consumed
        return context

templates/production/for_ing_delete.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/inventory.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Inventory Management{% endblock %}

{% block content %}

<div class="delete-page">
    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete ingredient - "{{ object.ingredient.name }}" for formula - {{object.formula.name}}?</p>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn-danger">Yes, delete</button>
    </form>
    <div>
        <a href="{% url 'production:formula-detail' object.formula.pk %}">Cancel</a>
    </div>
</div>

{% endblock %}

{% block script %} {% endblock %}

templates/production/formula_create.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/production.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Inventory Update{% endblock %}

{% block content %}
<div class="for-container">
    <div class="for-list">
        <h2>Recent Formulas</h2>
        <div class="formula-list">
            <table class="for-table">
                <tr>
                    <th>S.N.</th>
                    <th>Formula Name</th>
                    <th>Created Date</th>
                    <th>Created By</th>
                    <th>Active</th>
                    <th>Action</th>
                </tr>
                {% for formula in formulas %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ formula.name }}</td>
                    <td> {{ formula.updated_at }}</td>
                    <td>{{ formula.created_by }}</td>
                    <td>{{ formula.is_active }}</td>
                    <td>
                        <div>
                            <span class="update-item"><a href="{% url 'production:formula-detail' formula.pk %}">Update</a></span>
                         <span class="delete-item"><a href="{% url 'production:formula-delete' formula.pk %}">Delete</a></span>
                         </div>
                    </td>
                </tr>
                {% empty %}
                <tr><td colspan="3">No data available</td></tr>
                {% endfor %}
            
            </table>
        </div>
    </div>

    <div class="form-create">
    
    <h2>Create New Formula</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <h2>Add Ingredients To Formula</h2>
    {{ ingredient_formset.management_form }}
    
        <div class="ingredient-form">
            <table>
                {% for form in ingredient_formset %}
                <tr>
                    <td>{{form.ingredient.label_tag}}</td>
                    <td>{{form.ingredient}}</td>
                    <td>{{form.percentage.label_tag}}</td>
                    <td>{{form.percentage}}</td>
                </tr>
                {% endfor %}   
            </table>
        </div>
    <div class="btn-formula">
        <!-- <button type="button" id="add-form">Add Ingredient</button> -->
        <button type="submit">Save Formula</button>
    </div>
</form>
</div>
</div>


{% endblock %}

{% block script %} {% endblock %}

templates/production/formula_delete.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/inventory.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Inventory Management{% endblock %}

{% block content %}

<div class="delete-page">
    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete formula - "{{ object.name }}"?</p>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn-danger">Yes, delete</button>
    </form>
    <div>
        <a href="{% url 'production:formula-create' %}">Cancel</a>
    </div>
</div>

{% endblock %}

{% block script %} {% endblock %}

templates/production/formula_detail.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/production.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Formula Detail{% endblock %}

{% block content %}

<div class="formula-detail">
    <h1><strong>Detail On Formula :</strong> {{formula.name}}</h1>
    <div class="formula-detail-top">
        <p><strong>Description on Formula:</strong> {{ formula.description }}</p>
        <p><strong> Formula Created at:</strong> {{ formula.created_at }}</p>
        <p><strong> Formula Created By:</strong> {{ formula.created_by }}</p>
        <p><strong> Total Ingredients:</strong> {{ items.count }}</p>
        
    </div>

    <h2>Ingredients Used</h2>
    <div class="formula-detail-table">
        <table>
        <tr>
            <th>S.N.</th>
            <th>Ingredient Name</th>
            <th>Unit</th>
            <th>Percentage</th>
            <th>Current Stock</th>
            <th>Stock Required</th>
            <th>Action</th>
        </tr>
        {% for item in items %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{ item.ingredient.name }}</td>
                <td>{{item.ingredient.unit}}</td>
                <td>{{ item.percentage }}</td>
                <td>{{item.ingredient.current_stock}}</td>
                <td>{{item.ingredient.current_stock}}</td>
                <td><a href="{% url 'production:foring-delete' formula_id=formula.pk pk=item.pk %}">Delete</a></td>
            </tr>
        {% empty %}
            <tr><td colspan="2">No ingredients listed.</td></tr>
        {% endfor %}
        </table>
    </div>
    <div class="new-formset">
        
    </div>
    <div class="add-formula-ing">
        <form action="">
            <button class="add-ingredient">
                <span class="material-symbols-outlined">
                    add
                </span>
                Add Ingredient
            </button>
        </form>
    </div>
</div>


{% endblock %}

{% block script %} {% endblock %}

templates/production/production.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/production.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Formula Detail{% endblock %}

{% block content %}

<div class="prod-container">
    <div class="prod-list">
        <h2>Recent Productions</h2>
        <div>
            <table class="prod-table">
                <tr>
                    <th>S.N.</th>
                    <th>Feed Formula</th>
                    <th>Unit</th>
                    <th>Quantity</th>
                    <th>Date</th>
                    <th>Produced By</th>
                    <th>Details</th>
                </tr>
                {% for production in productions %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{production.formula}}</td>
                    <td>{{production.unit}}</td>
                    <td>{{production.batch_size}}</td>
                    <td>{{production.production_date}}</td>
                    <td>{{production.produced_by}}</td>
                    <td>
                        <span><a href="{% url 'production:production-detail' production.id %}">Details</a></span>
                    </td>
                </tr>
                {% empty %}
                <div>No Entries Found</div>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="prod-form">
        <h2>Start Production</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{prod_form}}
            <input type="submit" value="Start Production">
        </form>
    </div>
</div>


{% endblock %}

{% block script %} {% endblock %}

templates/production/production_detail.html
{% extends 'basic/index.html' %}
{% load static %}

{% block stylesheet %}
   <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
   <link href="{% static 'css/production.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}Formula Detail{% endblock %}

{% block content %}

<div class="prod-detail-container">
    <h1>Production Detail for {{production.formula}} formula</h1>
    <div class="prod-detail">
        <div class="prod-top">
            <p>Production Formula: <strong>{{production.formula}}</strong></p>
            <p>Production Unit: <strong>{{production.get_unit_display}}</strong></p>
            <p>Production Batch Size: <strong>{{production.batch_size}}</strong></p>
            <p>Production Date: <strong>{{production.production_date}}</strong></p>
            <p>Production By: <strong>{{production.produced_by}}</strong></p>
        </div>
        <table class="prod-table">
            <h2>Ingredients Used</h2>
            <tr>
                <th>S.N.</th>
                <th>Ingredient</th>
                <th>Unit</th>
                <th>Percentage</th>
                <!-- returns in Kg -->
                <th>Previous Stock</th>
                <th>Consumed Stock</th>
                <th>Current Stock</th>
            </tr>
            {% for ingredient in ingredients %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{ingredient.ingredient}}</td>
                <td>{{ingredient.unit}}</td>
                <td>{{ingredient.percentage}}</td>
                <td>{{ingredient.previous_stock}}</td>
                <td>{{ingredient.consumed_quantity}}</td>
                <td>{{ingredient.current_stock}}</td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td>Total</td>
                <td></td>
                <td>{{total_percentage}}</td>
                <td></td>
                <td>{{total_consumed}}</td>
                <td></td>
            </tr>
        </table>
    </div>
</div>


{% endblock %}

{% block script %} {% endblock %}